services:
  url-shortener:
    build: .
    image: url-shortener:latest
    container_name: url-shortener-app
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      APP_BASE_URL: http://localhost:8082
    restart: unless-stopped
